0006620: Turn on UNLOGGED table mode during initial load into an empty PostgreSQL table
JumpMind/symmetric-ds pull request #201
Opened 2024-10-18 14:12 UTC by pavel-jm

Logging table attribute, change detection and 
UNLOGGED table mode during initial load into an empty PostgreSQL table

2024-10-21 12:30 UTC, erilong requested changes

2024-10-21 12:30 UTC, erilong commented on symmetric-db/src/main/java/org/jumpmind/db/platform/postgresql/PostgreSqlDdlBuilder.java
> +    protected void writeTableCreationStmt(Table table, StringBuilder ddl) {
It would be better to add a method to AbstractDdlBuilder like writeTableAfterClause() that does nothing but can be overridden here to write "UNLOGGED".  That way this class doesn't miss out on any changes to parent in this method.

2024-10-21 12:30 UTC, erilong commented on symmetric-jdbc/src/main/java/org/jumpmind/db/platform/postgresql/PostgreSqlDdlReader.java
> +        StringBuilder sqlBuilder = new StringBuilder();
The compiler already does this optimization, so it's fine to use plus (+) syntax.

2024-10-21 12:30 UTC, erilong commented on symmetric-jdbc/src/main/java/org/jumpmind/db/platform/postgresql/PostgreSqlDdlReader.java
> +        PreparedStatement command = null;
I like variables named after the object so it's easy to know what it is.  The "ps" for prepared statement and "rs" for result set is easy to read, but having to map "command" to prepared statement makes my brain work harder.

2024-10-21 12:30 UTC, erilong commented on symmetric-db/src/test/java/org/jumpmind/db/io/DatabaseXmlUtilTest.java
> +        // Arrange
Comments like these don't add anything for me and could be removed.

2024-10-21 12:30 UTC, erilong commented on symmetric-db/src/test/java/org/jumpmind/db/io/DatabaseXmlUtilTest.java
> +        // Assert
Comments for unused code should be removed.

2024-10-21 12:30 UTC, erilong commented on symmetric-db/src/main/java/org/jumpmind/db/platform/postgresql/PostgreSqlDdlBuilder95.java
> + * Overrides defaults to enable features introduced in the PostgreSQL version 9.5 https://www.postgresql.org/docs/release/9.5.0/
We're already in a class whose responsibility is to override for features in version 9.5, so comments like these don't add anything for me.

2024-10-21 12:30 UTC, erilong commented on symmetric-core/src/main/java/org/jumpmind/symmetric/extract/SelectFromSymDataSource.java
> +        // parameterService.is(ParameterConstants.INITIAL_LOAD_DEFER_CREATE_CONSTRAINTS, false);
Remove commented out code.

2024-10-28 12:01 UTC, pavel-jm commented on symmetric-jdbc/src/main/java/org/jumpmind/db/platform/postgresql/PostgreSqlDdlReader.java
> +        StringBuilder sqlBuilder = new StringBuilder();
Noted! Reversed this method to original code.

2024-10-28 12:01 UTC, pavel-jm commented on symmetric-jdbc/src/main/java/org/jumpmind/db/platform/postgresql/PostgreSqlDdlReader.java
> +        PreparedStatement command = null;
Noted! Reversed this method to original code.

2024-10-28 12:01 UTC, pavel-jm commented on symmetric-db/src/test/java/org/jumpmind/db/io/DatabaseXmlUtilTest.java
> +        // Arrange
Noted! Removed

2024-10-28 12:01 UTC, pavel-jm commented on symmetric-db/src/test/java/org/jumpmind/db/io/DatabaseXmlUtilTest.java
> +        // Assert
Noted! Removed

2024-10-28 12:02 UTC, pavel-jm commented on symmetric-db/src/main/java/org/jumpmind/db/platform/postgresql/PostgreSqlDdlBuilder95.java
> + * Overrides defaults to enable features introduced in the PostgreSQL version 9.5 https://www.postgresql.org/docs/release/9.5.0/
Noted! Updated to the link to original documentation

2024-10-28 12:02 UTC, pavel-jm commented on symmetric-core/src/main/java/org/jumpmind/symmetric/extract/SelectFromSymDataSource.java
> +        // parameterService.is(ParameterConstants.INITIAL_LOAD_DEFER_CREATE_CONSTRAINTS, false);
Noted! Removed

2024-10-28 14:54 UTC, erilong approved these changes

2024-11-20 20:37 UTC, merged